# fly.toml app configuration file generated for tricks on 2023-08-16T20:32:35-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tricks"
primary_region = "ord"
console_command = "/code/manage.py shell"

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/staticfiles"
  url_prefix = "/static/"
