# Generated by Django 4.2.3 on 2023-07-21 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suit",
                    models.CharField(
                        choices=[
                            ("Hearts", "Hearts"),
                            ("Diamonds", "Diamonds"),
                            ("Clubs", "Clubs"),
                            ("Spades", "Spades"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("Jack", "Jack"),
                            ("Queen", "Queen"),
                            ("King", "King"),
                            ("Ace", "Ace"),
                        ],
                        max_length=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bet", models.IntegerField(blank=True)),
                ("wins", models.IntegerField(default=0)),
                ("points", models.IntegerField(default=0)),
                ("hand", models.ManyToManyField(blank=True, to="main.card")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cur_round", models.IntegerField(default=1)),
                ("players", models.ManyToManyField(to="main.player")),
                (
                    "trump",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="main.card"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active_player",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_player",
                        to="main.player",
                    ),
                ),
                ("cards_played", models.ManyToManyField(blank=True, to="main.card")),
                (
                    "round",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="main.round"
                    ),
                ),
                (
                    "winner",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="winner",
                        to="main.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "g_rounds",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.round"
                    ),
                ),
                (
                    "players",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.player"
                    ),
                ),
            ],
        ),
    ]
