# Generated by Django 4.2.3 on 2023-07-21 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_game_g_rounds_remove_game_players_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.player",
            ),
        ),
    ]
