# Generated by Django 4.2.3 on 2023-07-21 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_card_player"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="playe_pos",
            new_name="player_pos",
        ),
    ]
