# Generated by Django 4.2.3 on 2023-07-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_rename_playe_pos_player_player_pos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="bet",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
