# Generated by Django 4.2.3 on 2023-07-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_game_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="bet",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
