# Generated by Django 4.2.3 on 2023-07-23 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_player_bet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="round",
            name="cur_round",
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name="round",
            name="trump",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.card",
            ),
        ),
    ]
