# Generated by Django 4.2.3 on 2023-07-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_round_cur_round_alter_round_trump"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="order",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
