# Generated by Django 4.2.3 on 2023-07-26 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_card_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="order",
        ),
        migrations.RemoveField(
            model_name="player",
            name="active",
        ),
    ]
