# Generated by Django 4.2.3 on 2023-08-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_remove_card_order_remove_player_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="status",
            field=models.TextField(
                blank=True,
                choices=[
                    ("d", "Deck"),
                    ("h", "Hand"),
                    ("p", "Played"),
                    ("t", "Trump"),
                    ("i", "In Play"),
                ],
                default="d",
            ),
        ),
    ]
