# Generated by Django 4.2.3 on 2023-08-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_card_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="in_play",
            field=models.BooleanField(default=False),
        ),
    ]
