# Generated by Django 4.2.3 on 2023-08-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_game_in_play"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="player_pos",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
