# Generated by Django 4.2.3 on 2023-08-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_player_player_pos"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="turn",
            field=models.IntegerField(default=1),
        ),
    ]
