# Generated by Django 4.2.3 on 2023-08-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_game_turn"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="status",
            field=models.TextField(
                choices=[("d", "Deal"), ("b", "Bet"), ("p", "Play")], default="d"
            ),
        ),
    ]
