# Generated by Django 4.2.3 on 2023-08-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_round_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="wins",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Trick",
        ),
    ]
