# Generated by Django 4.2.3 on 2023-08-08 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0016_player_wins_delete_trick"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="points",
            new_name="score",
        ),
        migrations.RemoveField(
            model_name="card",
            name="game",
        ),
        migrations.RemoveField(
            model_name="card",
            name="player",
        ),
        migrations.RemoveField(
            model_name="card",
            name="status",
        ),
        migrations.RemoveField(
            model_name="game",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="game",
            name="in_play",
        ),
        migrations.RemoveField(
            model_name="game",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="game",
            name="turn",
        ),
        migrations.RemoveField(
            model_name="game",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="player",
            name="game",
        ),
        migrations.RemoveField(
            model_name="player",
            name="player_pos",
        ),
        migrations.RemoveField(
            model_name="round",
            name="cur_round",
        ),
        migrations.RemoveField(
            model_name="round",
            name="game",
        ),
        migrations.RemoveField(
            model_name="round",
            name="status",
        ),
        migrations.AddField(
            model_name="game",
            name="bet_turn",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="num_of_rounds",
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name="game",
            name="players",
            field=models.ManyToManyField(to="main.player"),
        ),
        migrations.AddField(
            model_name="game",
            name="rounds",
            field=models.ManyToManyField(blank=True, null=True, to="main.round"),
        ),
        migrations.AddField(
            model_name="player",
            name="cur_card",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="cur_card", to="main.card"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="hand",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="hand", to="main.card"
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="bet_sum",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="round",
            name="cards_dealt",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="round",
            name="dealer",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dealer",
                to="main.player",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="round",
            name="deck",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="deck", to="main.card"
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="num",
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="round",
            name="players",
            field=models.ManyToManyField(related_name="players", to="main.player"),
        ),
        migrations.AddField(
            model_name="round",
            name="table",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="table", to="main.card"
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="trick",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="trick", to="main.card"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="bet",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="trump",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trump",
                to="main.card",
            ),
        ),
    ]
