# Generated by Django 4.2.3 on 2023-08-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_rename_points_player_score_remove_card_game_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="players",
            field=models.ManyToManyField(blank=True, null=True, to="main.player"),
        ),
    ]
