# Generated by Django 4.2.3 on 2023-08-08 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_alter_game_players"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="cur_card",
        ),
        migrations.AddField(
            model_name="player",
            name="cur_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cur_card",
                to="main.card",
            ),
        ),
    ]
