# Generated by Django 4.2.3 on 2023-08-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_remove_player_cur_card_player_cur_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="rank",
            field=models.CharField(
                choices=[
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                    ("11", "Jack"),
                    ("12", "Queen"),
                    ("13", "King"),
                    ("14", "Ace"),
                ],
                max_length=5,
            ),
        ),
    ]
