# Generated by Django 4.2.3 on 2023-08-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_player_created_player_updated_alter_card_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="round",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="round",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
