# Generated by Django 4.2.3 on 2023-08-09 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_game_created_game_updated_round_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="round",
            name="trick",
        ),
        migrations.AddField(
            model_name="round",
            name="trick",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trick",
                to="main.card",
            ),
        ),
    ]
