# Generated by Django 4.2.3 on 2023-08-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_remove_round_trick_round_trick"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="bet_pos",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="play_pos",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
