# Generated by Django 4.2.3 on 2023-08-09 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_player_bet_pos_player_play_pos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="round",
            name="players",
        ),
        migrations.AddField(
            model_name="round",
            name="game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.game",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="rounds",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="cur_rounds", to="main.round"
            ),
        ),
    ]
