# Generated by Django 4.2.3 on 2023-08-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_alter_game_num_of_rounds_alter_game_players_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="round",
            name="cards_dealt",
        ),
        migrations.AlterField(
            model_name="game",
            name="num_of_rounds",
            field=models.IntegerField(default=7),
        ),
    ]
