# Generated by Django 4.2.3 on 2023-08-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_remove_round_cards_dealt_alter_game_num_of_rounds"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="finished",
            field=models.BooleanField(default=False),
        ),
    ]
